name: my_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  speech_to_text: ^7.3.0
  dio: ^5.2.1
  # إضافة Coil/AsyncImage equivalent في Flutter هو cached_network_image
  cached_network_image: ^3.2.3
  # لتسهيل الـ state management للـ Favorites
  provider: ^6.0.7
  # تم إضافة url_launcher
  url_launcher: ^6.1.10
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
